https://www.youtube.com/watch?v=ZB7BZMhfPgk&t=4530s

http://kestrel.nmt.edu/~raymond/software/python_notes/paper003.html

In [4]:
import numpy as np

In [22]:
a = np.array([1, 2, 3])

In [24]:
x = np.array([[1,3,4,5], [6,7,8,9]])
print(x)

[[1 3 4 5]
 [6 7 8 9]]


In [26]:
x.ndim

2

In [27]:
x.shape

(2, 4)

In [28]:
x.size

8

In [29]:
x.itemsize

4

In [25]:
x.dtype

dtype('int32')

In [33]:
# create array with reshape
arr = np.arange(14).reshape(2, 7)
print(arr)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]


In [37]:
# get the first axes last element [row, col]

arr[0, -1]

6

In [40]:
# get a specific row

arr[0, :]

array([0, 1, 2, 3, 4, 5, 6])

In [39]:
# get a specific column 

arr[:, 2]

array([2, 9])

In [45]:
# complex slicing [startIndex:endIndex:stepsize] 
# get the middle odd nums

arr[1, 0:6:2]

array([ 7,  9, 11])

In [ ]:
# Adding, Removing, and Sorting elements 

In [46]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [47]:
# sorting
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [49]:
# concatenate
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [57]:
conc = np.concatenate((x, y), axis=0)
conc

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
# changing element from the array above 6 to 7
conc[2, -1] = 7
conc

array([[1, 2],
       [3, 4],
       [5, 7]])

In [65]:
# example of 3D array

In [12]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# get specific element (work outside in)

b[0, 1, -1]

4

In [ ]:
#SLICING

In [16]:
x = np.array([10, 11, 12, 13, 14])

In [17]:
x[1:3]

array([11, 12])

In [20]:
# grab first three element 

x[:3]

array([10, 11, 12])

In [21]:
# grab last two elements

x[-2:]

array([13, 14])

In [22]:
# grab every other element

x[::2]

array([10, 12, 14])

In [27]:
a = np.arange(56).reshape(7, 8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]]


In [29]:
a[0, 3:5]

array([3, 4])

In [69]:
a[0, 3:5:1]

array([3, 4])

In [30]:
# after 4 grab all and then from that grab only columns after 4th 
a[4: , 4:]

array([[36, 37, 38, 39],
       [44, 45, 46, 47],
       [52, 53, 54, 55]])

In [31]:
a[2::2, ::2]

array([[16, 18, 20, 22],
       [32, 34, 36, 38],
       [48, 50, 52, 54]])

In [32]:
y = np.arange(25).reshape(5, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [99]:
# grab last row

y[-1, :]

array([20, 21, 22, 23, 24])

In [67]:
# grab col 1 and 3

y[:, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [65]:
y[:, 1::]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [82]:
# grab elem 5, 7, 15, and 17

y[1::2, :3:2]

array([[ 5,  7],
       [15, 17]])

In [92]:
# grab corner elem 0, 4, 20, 24 

y[::4, ::4]

array([[ 0,  4],
       [20, 24]])

In [98]:
# same as above
y[0::4, 0::4]

array([[ 0,  4],
       [20, 24]])

In [110]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [112]:
#grab elems 5,6,10,11

y[1:3, 0:2]

array([[ 5,  6],
       [10, 11]])

In [101]:
y[-2:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [108]:
str = "Hello"
str[::-1]

'olleH'

# Fancy Indexing


In [115]:
a = np.arange(0, 80, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [116]:
# grab elem from the list of indices positions

x = [1, 2, -3]
y = a[x]
print(y)

[10 20 50]


In [117]:
# assign value to elem

a[x] = 99
a

array([ 0, 99, 99, 30, 40, 99, 60, 70])

In [118]:
# masking

b = a < 90
b

array([ True, False, False,  True,  True, False,  True,  True])

In [5]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [163]:
# grab elem 2, 13, 16, 19
# the indices are separated to two list

arr[[0, 2, 3, -2], [2, 3, 1, -1]]

array([ 2, 13, 16, 19])

In [6]:
#get elems divisible by 3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr % 3 == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [32]:
arr[[0, 0, 1, 1, 2, 3, 3, 4, 4], [0, 3, 1, -1, 2, 0, 3, 1, -1]]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [31]:
#get elems divisible by 3
arr[arr%3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

# Array Calculation Methods

In [38]:
# Sum method and other various operation methods check Numpy doc

a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
#adds all the elem
a.sum()

21

In [40]:
#adds the col elems
a.sum(axis=0)

array([5, 7, 9])

In [41]:
#adds the row elems
a.sum(axis=1)

array([ 6, 15])

In [46]:
#memory
arr.dtype

dtype('int32')

int32 or int64 means every element is a 32bit integer 
1 byte = 8 bits
32/8 = 4